version: 2.1
jobs:
  build:
    docker:
      - image: node:lts-alpine3.12
    steps:
      - checkout
      - run:
          name: Installing Yarn
          command: |
            npm install -g yarn
      - run:
          name: Installing Dependencies
          command: |
            yarn install
      - run:
          name: Run Tests
          command: |
            yarn run test

